export const ActionTypes = {
    FETCH_GAMES: "FETCH_GAMES",
    SELECT_GAME: "SELECT_GAME",
    FETCH_CATEGORIES: "FETCH_CATEGORIES",
    FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",
    SET_CATEGORY_FILTERS: "SET_CATEGORY_FILTERS",
    SET_PLATFORM_FILTER: "SET_PLATFORM_FILTER",
    SET_SORT_BY: "SET_SORT_BY",
    SET_SEARCH_TERM: "SET_SEARCH_TERM",
    FETCH_GAMES_ERROR: "FETCH_GAMES_ERROR",
    REMOVE_SELECTED_GAME: "REMOVE_SELECTED_GAME"
}